version: "3"

services:
    redis:
        image: "redis:alpine"
        
        ports:
            - 6379:6379
            
        networks:
            - microservices

    server:
        build:
            context: .
            dockerfile: docker/grpc-server/Dockerfile 
          
        ports:
            - "50051:50051"
        
        networks:
            - microservices
            

    app:
        build:
            context: .
            dockerfile: docker/flask-app/Dockerfile

        ports:
            - "3001:3001"

        networks:
            - microservices

        volumes:
            - ./core:/service/consumer/

        depends_on:
            - redis
            - worker
            - server


    worker:
        build:
            context: .
            dockerfile: docker/worker/Dockerfile

        networks:
            - microservices

        depends_on:
            - redis


    rq-dashboard:
        image: jaredv/rq-docker:0.0.2 
        command: rq-dashboard --redis-url redis://redis:6379/0
        ports:
            - 9181:9181
        
        networks:
            - microservices

        depends_on:
            - redis

networks:
    microservices:
      driver: bridge
